/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'firestar' at '3/13/16 12:11 AM' with Gradle 2.11
 *
 * @author firestar, @date 3/13/16 12:11 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
